### ISSUE TITLE
Log indicates that a shrinkwrap file was created, but its not there

### ISSUE THREAD

**Issue by kumavis** [dominykas/allow-scripts#50]
log
```
npm notice created a lockfile as npm-shrinkwrap.json. You should commit this file.
```

dir
```
➜ la
total 120K
drwxrwxr-x   7 xyz xyz 4.0K Dec  8 15:15 .git
-rw-rw-r--   1 xyz xyz   13 Dec  8 15:14 .gitignore
drwxrwxr-x 308 xyz xyz  12K Dec  8 15:14 node_modules
-rw-rw-r--   1 xyz xyz  208 Dec  8 15:13 package.json
-rw-rw-r--   1 xyz xyz  94K Dec  8 15:13 yarn.lock
```

**Comment by dominykas** [comment]
At the moment, this is using the shrinkwrap to reconstruct the module tree - if one does not already exist, it will delete it afterwards to keep the state intact.

This is probably no longer necessary and could be rewritten to use @npmcli/arborist instead, but I'll wait until npm 7 is mainstream or maybe until node 10 is EOL before doing that.

**Comment by dominykas** [comment]
I'd accept a PR to suppress that message, though - to avoid further confusion.

**Comment by kumavis** [comment]
btw node 10 EOL is only 4 months away i think

**Comment by dominykas** [comment]
Yup.
